packages:
  - apps/*
  - services/*
  - packages/*

overrides:
  decode-uri-component: 0.5.0
  uuid: 11.1.1

allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260907.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260907.1'
  - '@cloudflare/workerd-linux-64@1.20260907.1'
  - '@cloudflare/workerd-linux-arm64@1.20260907.1'
  - '@cloudflare/workerd-windows-64@1.20260907.1'
  - '@cloudflare/workers-types@5.20260907.1'
  - miniflare@5.20260907.0-alpha
  - workerd@1.20260907.1
  - wrangler@4.129.1
  - '@types/node@26.5.0'
  - '@expo/cli@57.0.23'
  - '@expo/metro-file-map@57.0.3'
  - babel-preset-expo@57.0.11
  - expo-modules-core@57.0.17
  - expo-modules-jsi@57.1.0
  - expo@57.0.21
  - '@expo/ui@57.0.17'
  - expo-glass-effect@57.0.2
  - expo-router@57.0.20
